# Generated by Django 5.2.5 on 2025-08-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
