# Generated by Django 5.2.5 on 2025-08-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_livcategory_livproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LivCategory',
            new_name='LvivCategory',
        ),
        migrations.RenameModel(
            old_name='LivProduct',
            new_name='LvivProduct',
        ),
    ]
