# Generated by Django 5.2.5 on 2025-08-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_livcategory_lvivcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvivproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='main.lvivcategory'),
        ),
    ]
