# Generated by Django 5.2.5 on 2025-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lvivproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvivproduct',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
