# Generated by Django 5.2.5 on 2025-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lvivproduct_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lviv_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
