# Generated by Django 5.2.5 on 2025-08-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_lviv_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvivproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='LvivCategory',
        ),
        migrations.DeleteModel(
            name='LvivProduct',
        ),
    ]
